### PR TITLE
#68 update scaffold to use uikit template

### PR DESCRIPTION
**Pull request by chileap**
#68

### CODE REVIEW

**Comment by michaelbina** [comment]
@chileap i made a bunch of changes and tried to add the form field for attachment.  For some reason the image is not showing.  Partially because the attachment type doesn't automatically update the model code, but even after id o, for some reason the image doesn't show up for me and im not sure why.  Maybe you can fix that before I merge.

**Comment by chileap** [comment]
@michaelbina I will check this out now

**Comment by chileap** [comment]
@michaelbina I have finished it by adding model into scaffold generator too. so if you have field attachment it will add has_attached_file method of paperclip into model too. You can try it out

**Comment by michaelbina** [comment]
@chileap I'm still not sure why mine keeps showing like this when I upload something:


Screen Shot 2020-05-05 at 9 57 04 PM

**Comment by chileap** [comment]
@michaelbina let me try this out.

**Comment by chileap** [comment]
@michaelbina we got the mistake in form `= f.file_field :<%= attribute.name.titleize %>` it will show in form like `= f.file_field :Image` with capital I. That's why we got the error. However, I have check in show page, you have use `.<%= attribute.name %>.url(:thumbnail)` while I add in model as `thumb` and now I have changed that to `thumbnail` instead. So I think this should work now.

**Pull request merged**
